Implement packet Clone method
pion/rtp pull request #118
Opened 2021-02-03 13:13 UTC by ffmiyo

2021-02-03 17:35 UTC, Sean-Der commented
Woah this is awesome @ffmiyo! 

This might also be a good chance to do a `/v2` break. Would you be interested? We can get it into `pion/webrtc` right away as well. While it would be a breaking change, I don't see anyone that depends on it.

* https://github.com/pion/rtp/issues/90
* https://github.com/pion/rtp/issues/79

2021-02-03 19:50 UTC, ffmiyo commented
@Sean-Der Ah right, should've start with # 90. Sure, I'll try to do this.

2021-05-16 16:48 UTC, aler9 requested changes
must be updated to account for #119 by same author

2021-05-16 16:48 UTC, aler9 commented on packet_test.go
> +		PayloadOffset:  20,
must be updated to account for #119 by same author

2021-08-05 23:52 UTC, Sean-Der approved these changes

2021-08-05 23:52 UTC, merged